using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Flotacion : MonoBehaviour
{
    public float floatStrength = 10.0f; // La fuerza del movimiento
    public float speed = 5.0f; // La velocidad de oscilaci贸n

    private Vector3 startPos;

    // Start is called before the first frame update
    void Start()
    {
        startPos = transform.position; // Guarda la posici贸n inicial del objeto
    }

    // Update is called once per frame
    void Update()
    {
        // Calcula la posici贸n Y utilizando la funci贸n sinusoidal para crear el movimiento oscilante
        float newY = startPos.y + Mathf.Sin(Time.time * speed) * floatStrength;
        transform.position = new Vector3(transform.position.x, newY, transform.position.z);
    }
}